org: chirakid
app: serverless-starter-poc
service: serverless-starter-poc
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

custom:
  serverless-offline:
    httpPort: 4000
    
functions:
  authorizerViaIDToken:
    handler: authorizer.viaIDToken
  function1:
    handler: index.handler
  test:
    handler: test.status
    events:
      - http:
          path: test/status
          method: get
          cors: true
      - http:
          path: test/status/internal
          method: get
          cors: true
          authorizer: authorizerViaIDToken
