org: chirakid
app: serverless-starter-poc
service: serverless-starter-poc
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
  test:
    handler: test.status
    events:
      - http:
          path: test/status
          method: get
          cors: true